### ISSUE TITLE
Add random seed for shadow feature

### ISSUE THREAD

**Issue by Himanshu4318** [chasedehan/BoostARoota#13]
#Add option to set random state while performing shuffling for shadow features. So that result can be generated again.

**Comment by chasedehan** [comment]
Since BoostARoota uses the random module, if you set the seed anywhere in your program, as long as you don't change the seed somewhere else, BoostARoota should use it. Example:

```python
import random
from boostaroota import BoostARoota

random.seed(4)
br = BoostARoota(metric='logloss')
br.fit(x, y)
```


If you do the above is it working for you? Does it solve your question?  Thanks for using it and for your feedback.

Check this from SO.
https://stackoverflow.com/questions/11526975/set-random-seed-programwide-in-python

**Comment by Himanshu4318** [comment]
Thanks!!
It fixed issue when all 
`random.seed(4)
br = BoostARoota(metric='logloss')
br.fit(x, y)`
this is in one cell of jupyter notebook.

**Comment by chasedehan** [comment]
Great!
